Adapt workflows -  Add id provider to auth - Add logout
InseeFr/Coleman-Management pull request #70
Opened 2024-02-01 12:24 UTC by EricThuaud

2024-02-01 13:59 UTC, Grafikart requested changes
Quelques petites remarques

2024-02-01 13:59 UTC, Grafikart commented on src/hooks/useAuth.ts
> +  return logout;
Tu peux simplifier return useOidc({ assertUserLoggedIn: true }).logout

2024-02-01 13:59 UTC, Grafikart commented on src/hooks/useAuth.ts
> +  return oidcTokens.decodedIdToken.inseegroupedefaut.includes(role);
Il manque pas un d et un l là ?

2024-02-01 13:59 UTC, Grafikart commented on src/hooks/useAuth.ts
> +      extraQueryParams: { kc_idp_hint: import.meta.env.VITE_IDENTITY_PROVIDER },
Jme demande si c'est utile vu que tu l'a mis au niveau du createOidc (jte laisse vérifier)

2024-02-01 14:12 UTC, EricThuaud commented on src/hooks/useAuth.ts
> +  return oidcTokens.decodedIdToken.inseegroupedefaut.includes(role);
Non j'ai rectifié le nom aux endroits ou cela apparait dans l'appli, le token porte bien un vecteur "inseegroupedefaut" (écriture française)

2024-02-02 10:17 UTC, Grafikart approved these changes

2024-02-02 10:18 UTC, merged