feat: add questioning page
InseeFr/Coleman-Management pull request #95
Opened 2024-10-30 10:57 UTC by RenauxLeaInsee

2024-11-19 14:28 UTC, Grafikart requested changes
Un petit changement concernant l'utilisation de watch() sinon c'est bon.

2024-11-19 14:28 UTC, Grafikart commented on src/ui/Contact/ContactFormDialog.tsx
> +                isEmpty={watch("lastName") === ""}
Cette approche risque de créer beaucoup de rerender je pense que dans ce cas là tu devrais passer par des champs contrôler ou brancher la logique de détection du vide directement dans Field

2024-11-19 14:28 UTC, Grafikart commented on src/ui/Form/Field.tsx
> +            ) : undefined
Essayer la syntaxe suivante : 

```
props.isEmpty && <IconButton sx={{ mr: 2 }} size="small" onClick={props.onResetField}>
                <CloseIcon />
              </IconButton>
```

2024-11-19 14:28 UTC, Grafikart commented on src/ui/Questioning/StatesCard.tsx
> +      toggleDialog(undefined);
Ce undefined me semble bizarre, il faudrait avoir un état "closed" plutôt histoire d'être cohérent

2024-11-27 13:23 UTC, Grafikart approved these changes

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Form/Field.tsx
> +    onResetField?: () => void;
"onReset" serait suffisant, je ne pense pas que "field" apporte de l'information ici

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Form/Field.tsx
> +            )
Conditionner l'affichage de ce endAdornment si onResetField est présent. Certains champs pourrait ne pas être reset

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Form/Field.tsx
> +        }}
Conditionner l'affichage de ce endAdornment si onResetField est présent. Certains champs pourrait ne pas être reset

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Form/Field.tsx
> +          ),
Conditionner l'affichage de ce endAdornment si onResetField est présent. Certains champs pourrait ne pas être reset

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Form/Field.tsx
> +    onResetField?: () => void;
Aussi, on pourrait se demander si il est pertinent d'exposer cette propriété. Le clique sur un "reset" devrait vider la valeur du champs (est donc plutôt déclencher un onChange à vide non ?

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Questioning/StatesCard.tsx
> +                {new Date(Date.parse(questioning.dateLastEvent)).toLocaleDateString()}
Créer un composant pour ça pour éviter la répétition 

```
<FormattedDate date={questioning.dateLastEvent}/>
```

2024-11-27 13:23 UTC, Grafikart commented on src/ui/Questioning/StatesCard.tsx
> +                  {new Date(Date.parse(questioning.dateLastCommunication)).toLocaleDateString()}
Créer un composant pour ça pour éviter la répétition 

```
<FormattedDate date={questioning.dateLastEvent}/>
```

2024-11-27 14:01 UTC, RenauxLeaInsee commented on src/ui/Form/Field.tsx
> +    onResetField?: () => void;
Bien vu, j'ai supprimé onResetField et j'utilise onChange à la place

2024-11-27 14:14 UTC, RenauxLeaInsee commented on src/ui/Form/Field.tsx
> +            )
Plus besoin si j'utilise onChange à la place (tous les fields ont une fonction onChange et d'après la maquette cette fonctionnalité doit toujours être présente lorsqu'il y a une valeur ) ^^

2024-11-27 14:15 UTC, merged